// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDoLeoBlazor.API.Context;

#nullable disable

namespace SistemaDoLeoBlazor.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231213234132_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaDoLeoBlazor.API.Entities.Operador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("admin")
                        .HasColumnType("bit");

                    b.Property<bool>("inativo")
                        .HasColumnType("bit");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("id");

                    b.ToTable("Operador");
                });

            modelBuilder.Entity("SistemaDoLeoBlazor.API.Entities.OperadorPermissoesTela", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("editar")
                        .HasColumnType("bit");

                    b.Property<bool>("excluir")
                        .HasColumnType("bit");

                    b.Property<bool>("novo")
                        .HasColumnType("bit");

                    b.Property<int>("operadorTelaId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("operadorTelaId")
                        .IsUnique();

                    b.ToTable("OperadorPermissoesTela");
                });

            modelBuilder.Entity("SistemaDoLeoBlazor.API.Entities.OperadorTela", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("operadorId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("operadorId");

                    b.ToTable("OperadorTela");
                });

            modelBuilder.Entity("SistemaDoLeoBlazor.API.Entities.OperadorPermissoesTela", b =>
                {
                    b.HasOne("SistemaDoLeoBlazor.API.Entities.OperadorTela", "operadorTela")
                        .WithOne("operadorPermissoesTela")
                        .HasForeignKey("SistemaDoLeoBlazor.API.Entities.OperadorPermissoesTela", "operadorTelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("operadorTela");
                });

            modelBuilder.Entity("SistemaDoLeoBlazor.API.Entities.OperadorTela", b =>
                {
                    b.HasOne("SistemaDoLeoBlazor.API.Entities.Operador", "operador")
                        .WithMany("telas")
                        .HasForeignKey("operadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("operador");
                });

            modelBuilder.Entity("SistemaDoLeoBlazor.API.Entities.Operador", b =>
                {
                    b.Navigation("telas");
                });

            modelBuilder.Entity("SistemaDoLeoBlazor.API.Entities.OperadorTela", b =>
                {
                    b.Navigation("operadorPermissoesTela");
                });
#pragma warning restore 612, 618
        }
    }
}
