// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDoLeoBlazor.API.Context;

#nullable disable

namespace SistemaDoLeoBlazor.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaDoLeoBlazor.API.Entities.Operador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("admin")
                        .HasColumnType("bit");

                    b.Property<bool>("inativo")
                        .HasColumnType("bit");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("id");

                    b.ToTable("Operador");
                });

            modelBuilder.Entity("SistemaDoLeoBlazor.API.Entities.OperadorTela", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<bool>("editar")
                        .HasColumnType("bit");

                    b.Property<bool>("excluir")
                        .HasColumnType("bit");

                    b.Property<bool>("novo")
                        .HasColumnType("bit");

                    b.Property<int>("operadorId")
                        .HasColumnType("int");

                    b.Property<int>("telaId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("operadorId");

                    b.HasIndex("telaId");

                    b.ToTable("OperadorTela");
                });

            modelBuilder.Entity("SistemaDoLeoBlazor.API.Entities.Tela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tela");
                });

            modelBuilder.Entity("SistemaDoLeoBlazor.API.Entities.OperadorTela", b =>
                {
                    b.HasOne("SistemaDoLeoBlazor.API.Entities.Operador", "operador")
                        .WithMany("operadorTelas")
                        .HasForeignKey("operadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDoLeoBlazor.API.Entities.Tela", "tela")
                        .WithMany("operadorTelas")
                        .HasForeignKey("telaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("operador");

                    b.Navigation("tela");
                });

            modelBuilder.Entity("SistemaDoLeoBlazor.API.Entities.Operador", b =>
                {
                    b.Navigation("operadorTelas");
                });

            modelBuilder.Entity("SistemaDoLeoBlazor.API.Entities.Tela", b =>
                {
                    b.Navigation("operadorTelas");
                });
#pragma warning restore 612, 618
        }
    }
}
